const products = [
  {
    id: 1,
    title: "Apple MacBook Air M2 13.6-inch",
    price: 1099.99,
    category: "Laptops",
    description: "Apple MacBook Air with M2 chip offers incredible performance with 18-hour battery life, a Liquid Retina display, and a lightweight, silent fanless design.",
    image: "src/assets/laptop-1.webp",
  },
  {
    id: 2,
    title: "Dell XPS 15 (9530) Laptop",
    price: 1899.99,
    category: "Laptops",
    description: "The Dell XPS 15 laptop combines powerful Intel Core i7 processors with a 15.6-inch OLED display, delivering top-notch performance and immersive visuals.",
    image: "src/assets/laptop-2.webp",
  },
  {
    id: 3,
    title: "Asus ROG Zephyrus G14",
    price: 1599.99,
    category: "Laptops",
    description: "Asus ROG Zephyrus G14 features Ryzen 9 processor, RTX 4060 graphics, and a 120Hz QHD display, ideal for gamers and creators.",
    image: "src/assets/laptop-3.webp",
  },
  {
    id: 4,
    title: "HP Spectre x360 14",
    price: 1499.99,
    category: "Laptops",
    description: "HP Spectre x360 14 offers an OLED touch display, Intel Evo certification, and exceptional battery life for mobile professionals.",
    image: "src/assets/laptop-4.webp",
  },
  {
    id: 5,
    title: "iPhone 15 Pro Max 256GB",
    price: 1299.99,
    category: "Phones",
    description: "iPhone 15 Pro Max with A17 Pro chip, 48MP camera system, titanium design, and all-day battery life for the ultimate smartphone experience.",
    image: "src/assets/phone-1.webp",
  },
  {
    id: 6,
    title: "Samsung Galaxy S24 Ultra 5G",
    price: 1399.99,
    category: "Phones",
    description: "Samsung Galaxy S24 Ultra with 200MP camera, 6.8-inch AMOLED 2X display, Snapdragon 8 Gen 3 processor, and S Pen for productivity on the go.",
    image: "src/assets/phone-2.webp",
  },
  {
    id: 7,
    title: "Google Pixel 8 Pro",
    price: 999.99,
    category: "Phones",
    description: "Google Pixel 8 Pro with Google Tensor G3 chip, pro camera system, and clean Android experience with 7 years of updates.",
    image: "src/assets/phone-3.webp",
  },
  {
    id: 8,
    title: "OnePlus 12 5G",
    price: 799.99,
    category: "Phones",
    description: "OnePlus 12 5G delivers ultra-smooth performance with Snapdragon 8 Gen 3, stunning display, and 100W super-fast charging.",
    image: "src/assets/phone-4.webp",
  },
  {
    id: 9,
    title: "LG UltraGear 34GP950G-B 34” Gaming Monitor",
    price: 1299.99,
    category: "Monitors",
    description: "LG UltraGear 34-inch curved gaming monitor with NVIDIA G-SYNC Ultimate, 1ms response time, and 144Hz refresh rate for an immersive gaming experience.",
    image: "src/assets/monitor-1.webp",
  },
  {
    id: 10,
    title: "Samsung Smart Monitor M8 32” 4K",
    price: 699.99,
    category: "Monitors",
    description: "Samsung Smart Monitor M8 with 4K UHD resolution, built-in apps like Netflix, YouTube, Office 365, and remote PC access for complete versatility.",
    image: "src/assets/monitor-2.webp",
  },
  {
    id: 11,
    title: "Dell UltraSharp U2723QE",
    price: 649.99,
    category: "Monitors",
    description: "Dell UltraSharp U2723QE offers 4K resolution, USB-C connectivity, and factory-calibrated color accuracy for professionals.",
    image: "src/assets/monitor-3.webp",
  },
  {
    id: 12,
    title: "ASUS ROG Swift OLED PG27AQDM",
    price: 1199.99,
    category: "Monitors",
    description: "ASUS ROG Swift OLED PG27AQDM features ultra-fast response, HDR10 support, and premium build quality for serious gamers.",
    image: "src/assets/monitor-4.webp",
  },
  {
    id: 13,
    title: "Logitech MX Keys Advanced Wireless Keyboard",
    price: 119.99,
    category: "Keyboards",
    description: "Logitech MX Keys features comfortable, illuminated keys, a premium build, and cross-device typing capabilities, perfect for advanced multitaskers.",
    image: "src/assets/keyboard-1.webp",
  },
  {
    id: 14,
    title: "SteelSeries Apex Pro TKL Wireless Keyboard",
    price: 249.99,
    category: "Keyboards",
    description: "SteelSeries Apex Pro TKL is the world's fastest keyboard with adjustable actuation switches, OLED display customization, and a premium aluminum frame.",
    image: "src/assets/keyboard-2.webp",
  },
  {
    id: 15,
    title: "Keychron K8 Wireless Mechanical Keyboard",
    price: 89.99,
    category: "Keyboards",
    description: "Keychron K8 offers wireless and wired connectivity, hot-swappable keys, and Mac/Windows compatibility with RGB backlight options.",
    image: "src/assets/keyboard-3.webp",
  },
  {
    id: 16,
    title: "Razer BlackWidow V4 Pro Mechanical Keyboard",
    price: 229.99,
    category: "Keyboards",
    description: "Razer BlackWidow V4 Pro features programmable macros, per-key RGB lighting, and tactile Green mechanical switches for a premium gaming experience.",
    image: "src/assets/keyboard-4.webp",
  }
];

export default products;
